// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyc3XU8wRxi879Fbb18GX1MkybkrLpU2k',
    appId: '1:465879871086:web:6d3032380a6a2c9ec5807f',
    messagingSenderId: '465879871086',
    projectId: 'documind-e0969',
    authDomain: 'documind-e0969.firebaseapp.com',
    storageBucket: 'documind-e0969.firebasestorage.app',
    measurementId: 'G-X0KEM36W45',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBulU3NXH13o951zYnU1dauaf3YrbxYpw8',
    appId: '1:465879871086:android:68deeef7f3f3b344c5807f',
    messagingSenderId: '465879871086',
    projectId: 'documind-e0969',
    storageBucket: 'documind-e0969.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQuOScMxlC3QedvWBb5K2KnSPOKkQBnM8',
    appId: '1:465879871086:ios:b31407fc43779aecc5807f',
    messagingSenderId: '465879871086',
    projectId: 'documind-e0969',
    storageBucket: 'documind-e0969.firebasestorage.app',
    iosBundleId: 'com.example.documind',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQuOScMxlC3QedvWBb5K2KnSPOKkQBnM8',
    appId: '1:465879871086:ios:b31407fc43779aecc5807f',
    messagingSenderId: '465879871086',
    projectId: 'documind-e0969',
    storageBucket: 'documind-e0969.firebasestorage.app',
    iosBundleId: 'com.example.documind',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyc3XU8wRxi879Fbb18GX1MkybkrLpU2k',
    appId: '1:465879871086:web:e92bda67068c7a26c5807f',
    messagingSenderId: '465879871086',
    projectId: 'documind-e0969',
    authDomain: 'documind-e0969.firebaseapp.com',
    storageBucket: 'documind-e0969.firebasestorage.app',
    measurementId: 'G-1K7QMF3K3Q',
  );
}
